baseurl = "http://footplusplus.com/"
# baseurl = "http://lambdaloop.com/footplusplus-website/"
languageCode = "en-us"
title = "Foot++"
theme = "hugo-creative-theme"
googleAnalytics = "UA-99584563-1"
publishDir = "docs"

[params]

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.

# All projects of the portfolio are defined in their own files.
# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
# folder into the 'data' directory at the root of this Hugo site.
# For more information take a look at the README.

# To provide some metadata for search engines feel free to add some
# information about you and your website.
name = "Foot++"
description = "A cheap FES device for footdrop treatment"
thumbnail = "img/header.jpg"

# The path must be relative to the static folder
favicon = "img/favicon.ico"


# Navigation
[params.navigation]
brand = "Foot++"
logo = "img/logo.png"

[params.navigation.links]
about     = "About"
# services  = "Services"
# portfolio = "Portfolio"
contact   = "Contact"


# Hero section
[params.hero]
# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
slogan     = "Footdrop treatment for everyone"
subtitle   = "Bringing freedom of mobility to those who previously could not afford it."
buttonText = "Find out more"


# About section
[params.about]
headline    = "An affordable FES device for footdrop treatment"
description = "Foot++ is developing an affordable Functional Electrical Stimulation (FES) device for treatment of footdrop (PENDING FDA 510K APPROVAL). We have created an accessible, affordable, and customizable FES device for footdrop as an alternative to the extremely expensive devices available on the market today."
# buttonText  = "Get started!"


# Team section
[params.team]
headline = "Team"

[[params.team.list]]
image = "img/pier_headshot_small.jpg"
title = "Pierluigi Mantovani"
description = "B.A. in Cognitive Science - UC Berkeley. Since graduating, Pierluigi has been doing neuroscience research at UCSF, focusing on electrical stimulation effects on the brain. Foot++ stems from his father's battle with MS and footdrop, in which he found that an affordable FES device was nonexistent."

[[params.team.list]]
image = "img/pierre_headshot_small.jpg"
title = "Pierre Karashchuk"
description = "B.A. in Computer Science and Statistics - UC Berkeley. Currently a PhD candidate in Neuroscience at University of Washington. He is interested in basic and applied neuroscience."

[[params.team.list]]
image = "img/peggy_headshot_small.jpg"
title = "Peggy Wang"
description = "Pursuing B.S. in Biomechanical Engineering - Stanford. Currently working on research projects at [Stanford BDML](http://bdml.stanford.edu/). She is especially invested in Foot++ because she herself has a slight hearing impairment, so she is committed to bringing affordable, non-intrusive medical devices to people in need."

[[params.team.list]]
image = "img/jnaulty_headshot_small.jpg"
title = "John Naulty Jr."
description = "B.A. in Cognitive Science - UC Berkeley. Cloud infrastructure engineer and hardware enthusiast. He is a member, and co-founder of NeurotechX, and enjoys being part of a community of curious researchers, engineers, and others interested in the intersection of neuroscience and technology."


# Portfolio modals
# [params.portfolio.modal]
# client = "Client"
# date = "Date"
# category = "Category"
# buttonText = "Close"

# Aside section
# [params.aside]
# 	headline = "Get the Creative Theme for Hugo"

# 	[params.aside.button]
# 		text = "Download now"
# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

# Contact section
[params.contact]
headline = "Let's Get In Touch!"
description = "Interested in testing out our device? Send us an email and we will get back to you as soon as possible!"
# phone = "661-993-0685"
email = "info@footplusplus.com"
mailing="yes"
# Google Maps section
# [params.location]
# latitude  = "37.8700259"
# longitude = "-122.2686634"
# maps_api_key = ""

# Social Media section
[params.social]
headline = "Follow Us on Social Media!"

[[params.social.list]]
link = "https://www.facebook.com/pg/FootPP"

[[params.social.list]]
link = "https://twitter.com/footplusplus"

[[params.social.list]]
link = "https://www.instagram.com/footplusplus/"

[[params.social.list]]
link = "https://www.linkedin.com/company/footplusplus"

# FAQ section
[params.faq]
headline = "Frequently Asked Questions"

[[params.faq.list]]
question = "Q: I want to test out your device. What should I do?"
answer = "A: Email us at [info@footplusplus.com](mailto:info@footplusplus.com) and someone from our team will contact you to see if we can set up a time and place. Also, please sign up for our mailing list and social media to keep up to date on our progress!"

[[params.faq.list]]
question = "Q: I really want to buy your device. When would this be available?"
answer = "A: At the moment, our device is still being developed. We also need to get FDA approval, which ensures that it’s medically approved and recommended for treatment, and that would take some time. However, we will love for you to support us on Indiegogo to help us develop our device! If you are sure you want to order a device once it comes out, please send us an email at [info@footplusplus.com](mailto:info@footplusplus.com) and we will be sure to notify you once we are ready to sell our product. Please sign up for our mailing list and social media to keep up to date on our progress!"

[[params.faq.list]]
question = "Q: How much would Foot++ improve my walking?"
answer = "A: Everybody has different reactions to stimulation and symptoms, so it would depend on your personal characteristics. However, [studies](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3919695/) have shown a significant increase of walking speed and comfort."

[[params.faq.list]]
question = "Q: Is Foot++ right for me?"
answer = "A: Since our device uses functional electrical stimulation (FES) on large muscle groups in the leg, a variety of neuromuscular diseases such as stroke, multiple sclerosis, Lumbar Degenerative Disease, muscular dystrophy, and others that cause foot drop could all be potentially tested using Foot++. Please contact us at [info@footplusplus.com](mailto:info@footplusplus.com) explaining your specific case and someone from our team will get back to you to set up a date and time to test!"
